### ISSUE TITLE
Configure New Relic Browser Agent with a copy->past snippet

### ISSUE THREAD

**Issue by mkoo-moncel** [newrelic-experimental/newrelic-nextjs-integration#1]
We're trying to add newrelic to an existing project using Next.js. I followed the instructions here and in the blog post (installed newrelic npm packages, modified package json scripts, injected script in `pages/_document, added newrelic.js config file` and am not seeing any data come through on new relic. 

When adding new relic via a copy/paste code snippet there are a bunch of parameters provided in addition to the license key that don't show here (accountID, trustKey, agentID, applicationID) and it's hard to imagine how this integration would work without that information. I wonder if there were steps missing from the instructions?

**Comment by matewilk** [comment]
Hey @mkoo-moncel,

Apologies for the late reply,

If you could create a sample repo where you can replicate the issue I could take a look and see if I can help.

**Comment by Fanoflix** [comment]
Same question, but slightly more information on my part. We are trying to integrate newrelic with a NextJS application.

We have tried all these methods.

**Method 1**
- Add inline Script by dangerouslysettingHTML in _app.tsx file

**Method 2**
- Add inline Script by dangerouslysettingHTML in _document.tsx file

Both of these methods fail. As soon as the application starts an error is thrown "newrelic is undefined" (which is not thrown if we import the script from a js file as opposed to using the script inline.

**Comment by Fanoflix** [comment]
Hello @matewilk Thanks for the quick reply.

I removed the `<script>` tags manually and then pasted the remaining script in `dangerouslySetInnerHTML`. When I try to do this, I still get the error '

As for `newrelic.getBrowserTimingHeader` method, I am not aware of it except for this article: https://newrelic.com/blog/how-to-relic/nextjs-monitor-application-data.

I tried the steps in this article but I was at a loss about where did the author ever specify the specific agent (through entityGuid or any other thing)?

**Comment by matewilk** [comment]
Hey @Fanoflix 
Sorry if I didn't make myself clear in the blog post.

the `broswerTimingHeader` returned from the below snippet, which you can also find the example of in the [_document.tsx](https://github.com/newrelic-experimental/newrelic-nextjs-integration/blob/main/pages/_document.tsx) file IS the Newrelic Browser agent

```js
const browserTimingHeader = newrelic.getBrowserTimingHeader({
  hasToRemoveScriptWrapper: true,
  allowTransactionlessInjection: true
});
```
The `hasToRemoveScriptWrapper: true` property tells the [`getBrowserTimingHeader`](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/api-guides/nodejs-agent-api/#browserTimingHeader) method to return the script without `script` tags.

For more details please see this [link](https://docs.newrelic.com/docs/apm/agents/nodejs-agent/extend-your-instrumentation/browser-monitoring-nodejs-agent/) as well.

You can simply pass it to `dangerouslySetInnerHTML` like it is done in _document.tsx file [_document.tsx](https://github.com/newrelic-experimental/newrelic-nextjs-integration/blob/main/pages/_document.tsx) 

```js
<script
  type="text/javascript"
  dangerouslySetInnerHTML={{ __html: this.props.browserTimingHeader }}
/>
```

And it passes the browser agent as a script without `script` wrapper to the `<script>` tag

Let me know if it helps

**Comment by Fanoflix** [comment]
Hello @matewilk ,

Sorry for the late reply.

I am not sure if I missed something or not, but where do we specify which entity the data gets sent to? I understood the snippets you have posted and I understood all that from the blog post, but I failed to find a reference/script to the actual entity that I wish to use.

For instance we have 3 entities for each environment, dev qa and prod. Dynamically setting them up comes later, but where is the linkage between the agent script?

**Comment by matewilk** [comment]
Hey @Fanoflix 

I'm not entirely sure what you mean by an `entity` exactly but if I understand you question correctly,

There are three variables that specify where the data is sent:
- New Relic Account Id
- Application name
- License ingest key

Depending on the integration method, environment variables, config file, or a copy->paste snippet (in case of the browser agent where those are automatically filled in for you) would need to be set up with those variables in order to start sending data to NR.

Then based on that you would log in to your New Relic account and via the UI navigate to `Browser -> {your app name}` where you would find your application metrics.

I'd encourage you to read through the [docs](https://docs.newrelic.com/) to understand those things or contact New Relic support as it seems your question is beyond the scope of this repository's purpose.

**Comment by Fanoflix** [comment]
Hey @matewilk 
I have actually read the docs and I know where in the newrelic dashboard I can see the analytics coming in.

As I said, we're using the copy->paste snippet method. And as the original issue specified:

"When adding new relic via a copy/paste code snippet there are a bunch of parameters provided in addition to the license key that don't show here (accountID, trustKey, agentID, applicationID) and it's hard to imagine how this integration would work without that information. I wonder if there were steps missing from the instructions?"

Summarising it all, the simple question is, how do I integrate the newrelic browser agent with NextJS using the copy paste method?

**Comment by matewilk** [comment]
Sure,

I've found some bits and pieces of this information in the local history of this repo (and combined it with the commit you've mentioned about)

Here it goes:

### New Relic Browser Agent Integration

1. Log in to your New Relic account (if you don't have it yet, register for free [here](https://newrelic.com/signup))
2. Go to [https://one.newrelic.com](https://one.newrelic.com) and (in the top right corner) select *Add more data*
3. Select *New Relic Browser* from *Browser metrics* section
4. Tick *Copy/Paste Javascript code*, enter your app name, and click *Enable*
5. You should now have the New Relic Browser snippet available to you which should look something like this:
   <img width="909" alt="Screenshot 2021-11-08 at 14 45 37" src="https://user-images.githubusercontent.com/6328360/140762690-67fba0a9-6a9d-4959-9516-75fef61ed3e8.png">
6. Copy/paste the entire snippet to a `.js` file in your project (you can find the example in this repo under `/newrelic/newrelic-browser-agent.js` - see [here](https://github.com/newrelic-experimental/newrelic-nextjs-integration/commit/ed1a847b1d0d3921afb355fc9a462ffe2c437bd3#diff-28dafde5abf892185335fef5b955711d42f632918e5ccfbfcb1d2edd1c0b0fae))
7. **Important** - modify the script:
   1. remove `<script>` tags from the beginning and the end of the script
   2. replace all "\\" with "\\\\" - escape the escape character
8. Create a new React Component and import the New Relic Browser agent to the file
   1. see the example [here](https://github.com/newrelic-experimental/newrelic-nextjs-integration/commit/ed1a847b1d0d3921afb355fc9a462ffe2c437bd3#diff-8188b2b6a3ae427e6c2926ca434cf52148c7c714b3fd3fae5bfc3be06449d009) - you can simply copy/paste it (remember to change the path to your New Relic Browser agent script if it differs)
9. Add the newly created component (in this case `NewRelicSnippet`) to the `Head` of your app entry point, usually `_app.tsx` under `pages` directory
   1. see how to do it [here](https://github.com/newrelic-experimental/newrelic-nextjs-integration/commit/ed1a847b1d0d3921afb355fc9a462ffe2c437bd3#diff-a9827ce1be32c607c948881a89b99c592f752898f9c49e0dea0b7199eb151029) (file on the left of the commit history)
   2. IMPORTANT - I'd rather use `_document.tsx` file
10. Congratulations, you have now successfully integrated New Relic Browser agent with NextJs framework!

**THIS MIGHT BE VERY USEFUL TOO:**
In addition you can find a lot of useful information about injecting the browser agent script [here](https://github.com/newrelic/newrelic-node-nextjs/issues/62#issuecomment-1206198267) (sorry, totally forgot about this thread) - probably it's a good idea to read through the whole thread from the start so you know the context.

**Comment by Fanoflix** [comment]
Thanks @matewilk! This is exactly what we needed. We did figure out most of the steps you detailed by looking at the commit history. Any particular reason for using `_document.tsx` in point 9 - ii ?

**Comment by ptahdunbar** [comment]
Just a note that this approach needs refreshing for next13+ using the app directory model. 

The root [app/layout.js](https://beta.nextjs.org/docs/routing/pages-and-layouts#root-layout-required) replaces the [_app.js](https://nextjs.org/docs/advanced-features/custom-app) and [_document.js](https://nextjs.org/docs/advanced-features/custom-document)
