### ISSUE TITLE
Example references non-existent file

### ISSUE THREAD

**Issue by kevburnsjr** [newrelic-experimental/newrelic-nextjs-integration#20]
`newrelic.js` contains a comment at the top that reads:
```js
/**
 * New Relic agent configuration.
 *
 * See lib/config/default.js in the agent distribution for a more complete
 * description of configuration variables and their potential values.
 */
 ```

However, neither this repository nor [the agent repository](https://github.com/newrelic/newrelic-node-nextjs) contains this file.  
Where is the config documentation?

**Comment by MariusOttersen** [comment]
You will find it in your local node_modules folder: `node_modules/newrelic/lib/config/default.js`
