### ISSUE TITLE
How to do client side configuration in Next.js 13 App folder app/layout.jsx? Instead of pages/_document.jsx

### ISSUE THREAD

**Issue by saicharan-gevme** [newrelic-experimental/newrelic-nextjs-integration#21]
I have an application, where I am completely using the new app folder for leveraging layouts, pages features.

So now when I tried to install NewRelic, I tried to use client side loading in `app/layout.jsx` from the guidance of `pages/_document.jsx` . But I was unsuccessful, in this regard, I kindly request to provide me a solution for integrating it in client side inside `app/layout.jsx` file.

**Comment by andrewmclagan** [comment]
This should work with the App Router:

```tsx
import newrelic from "newrelic";

export default function RootLayout({ children }: React.PropsWithChildren) {
  const browserTimingHeader = newrelic.getBrowserTimingHeader({
    hasToRemoveScriptWrapper: true,
  });

  return (
    <html lang="en">
      <body>
        <head>
          <script
            type="text/javascript"
            dangerouslySetInnerHTML={{ __html: browserTimingHeader }}
          ></script>
        </head>
        {children}
      </body>
    </html>
  );
}
```

Although it causes build errors. The npm package `newrelic` is a nodejs package. The `RootLayout` component is a server component, so this should work fine as its rendered on the server and sent to the client. But produces this error:

```
Module parse failed: Unexpected token (1:40)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
>                                  Apache License
|                            Version 2.0, January 2004
|                         http://www.apache.org/licenses/

Import trace for requested module:
../../../node_modules/.pnpm/newrelic@11.10.0/node_modules/newrelic/LICENSE
../../../node_modules/.pnpm/newrelic@11.10.0/node_modules/newrelic/ sync ^\.\/.*$
../../../node_modules/.pnpm/newrelic@11.10.0/node_modules/newrelic/index.js
./src/app/layout.tsx
```

There are issue with the NewRelic package not really possible to integrate with NewRelic and NextJS App Router. One would expect it to work considering its been released for over 2 years and its by far the most popular frontend framework. The mind boggles...

**Comment by danielspeixoto** [comment]
I am having the same problem here. Any updates?

**Comment by allyssonsantos** [comment]
Do we have any official example git repository that is working if app router?

**Comment by matewilk** [comment]
Please refer to this [layout.ts](https://github.com/matewilk/newrelic-nextjs-13-integration/blob/main/app/layout.tsx) file for the time being.
Additionally, you'll have to add [this line](https://github.com/matewilk/newrelic-nextjs-13-integration/blob/main/next.config.js#L4) to your `next.config.js` file.

It works for both Next.js 13 and 14

Hope this helps.

**Comment by bizob2828** [comment]
We have working examples from the Node.js agent team who maintains this.  You can look at this [FAQ](https://github.com/newrelic/newrelic-node-nextjs/blob/main/docs/faqs/browser-agent.md)
