### ISSUE TITLE
Is this repository still supported?

### ISSUE THREAD

**Issue by andrewmclagan** [newrelic-experimental/newrelic-nextjs-integration#23]
- There are multiple issues related to getting this package working with NextJs 13+ App Router.
- NextJS 13+ has been released for a very long time
- Its the most popular frontend framework
- 10s of pages in your docs link to it. 
- It simply does not work

We wasted a lot of time trying to get this working. Please at least state this does not support NextJS 13+ for browser

**Comment by matewilk** [comment]
Please refer to [newrelic-node-examples/nextjs-app-router](https://github.com/newrelic/newrelic-node-examples/tree/main/nextjs-app-router) repository for App Based router sample integration

**Comment by natsuki-engr** [comment]
moved to [nextjs/nextjs-app-router](https://github.com/newrelic/newrelic-node-examples/tree/main/nextjs/nextjs-app-router)
