### ISSUE TITLE
Monitoring build time

### ISSUE THREAD

**Issue by y-a-v-a** [newrelic-experimental/newrelic-nextjs-integration#6]
Would there also be a way to monitor the build phase of NextJS? As when we have metrics in NewRelic from the build phase, we would be able to compare that with former build phases.
Regards Vincent

**Comment by matewilk** [comment]
Hi @y-a-v-a 

Thanks for getting in touch.

This is not an officially supported repo although it uses official `newrelic` npm packages under the hood.
I think you should get an answer if you ask the question here:  https://github.com/newrelic/newrelic-node-nextjs

**Comment by y-a-v-a** [comment]
Thanks for the reply, I'll ask my question there! Cheers
